run: clean
	./00-controller.sh -b /rsgrps/bhurwitz/hurwitzlab/data/reference/patric_bacteria/1313.2945.fna -f /rsgrps/bhurwitz/kyclark/human-gut/fasta -o /rsgrps/bhurwitz/kyclark/human-gut/blast

clean:
	find . \( -name \*.conf -o -name \*.OU \) -exec rm {} \;
